/**
 * Pulls the Sleeper player dump and writes the eligible player pool to:
 *   - public/players.json  (static, client-side typeahead — no fuzzy matching,
 *                            just prefix/substring filtering over this list)
 *   - drizzle/seed-players.sql (idempotent upsert, run after migrations)
 *
 * Eligible = active QB/RB/WR/TE on an NFL roster (anyone who can score a
 * non-passing TD). Run with: npm run import:players
 */
import { writeFileSync, mkdirSync } from "fs";

const SLEEPER_PLAYERS_URL = "https://api.sleeper.app/v1/players/nfl";
const ELIGIBLE_POSITIONS = new Set(["QB", "RB", "WR", "TE"]);

type SleeperPlayer = {
  player_id: string;
  full_name?: string;
  first_name?: string;
  last_name?: string;
  team: string | null;
  position: string | null;
  status: string | null;
};

type EligiblePlayer = {
  id: string;
  fullName: string;
  team: string | null;
  position: string;
  searchName: string;
};

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''");
}

async function main() {
  const res = await fetch(SLEEPER_PLAYERS_URL);
  if (!res.ok) {
    throw new Error(`Sleeper API request failed: ${res.status} ${res.statusText}`);
  }
  const raw: Record<string, SleeperPlayer> = await res.json();

  const eligible: EligiblePlayer[] = Object.values(raw)
    .filter(
      (p): p is SleeperPlayer & { position: string; team: string } =>
        !!p.position &&
        ELIGIBLE_POSITIONS.has(p.position) &&
        !!p.team &&
        p.status === "Active",
    )
    .map((p) => {
      const fullName = p.full_name ?? `${p.first_name ?? ""} ${p.last_name ?? ""}`.trim();
      return {
        id: p.player_id,
        fullName,
        team: p.team,
        position: p.position as string,
        searchName: fullName.toLowerCase(),
      };
    })
    .sort((a, b) => a.fullName.localeCompare(b.fullName));

  if (eligible.length < 300) {
    // Sanity guard: Sleeper's schema/status values have changed before.
    throw new Error(
      `Only found ${eligible.length} eligible players — Sleeper response shape may have changed. Aborting before overwriting players.json.`,
    );
  }

  mkdirSync("public", { recursive: true });
  writeFileSync("public/players.json", JSON.stringify(eligible));

  mkdirSync("drizzle", { recursive: true });
  const values = eligible
    .map(
      (p) =>
        `('${sqlEscape(p.id)}', '${sqlEscape(p.fullName)}', ${
          p.team ? `'${sqlEscape(p.team)}'` : "NULL"
        }, '${sqlEscape(p.position)}', true, '${sqlEscape(p.searchName)}')`,
    )
    .join(",\n  ");

  const sql = `-- Generated by scripts/import-players.ts — do not edit by hand.
INSERT INTO players (id, full_name, team, position, active, search_name)
VALUES
  ${values}
ON CONFLICT (id) DO UPDATE SET
  full_name = excluded.full_name,
  team = excluded.team,
  position = excluded.position,
  active = excluded.active,
  search_name = excluded.search_name;
`;
  writeFileSync("drizzle/seed-players.sql", sql);

  console.log(`Wrote ${eligible.length} eligible players to public/players.json`);
  console.log("Wrote drizzle/seed-players.sql (run after migrations to populate the DB)");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
