/**
 * Refreshes the checked-in player pool from Sleeper's dump, writing:
 *   - public/players.json      (the picker's build-time fallback snapshot)
 *   - drizzle/seed-players.sql (idempotent upsert, run after migrations)
 *
 * The live, always-current pool is the `players` table, refreshed nightly by
 * lib/jobs/refresh.ts#refreshRoster and served to the picker via /api/players;
 * this script is the offline equivalent, for seeding a fresh DB and for keeping
 * the static fallback from drifting too far. Run with: npm run import:players
 *
 * **Merge, never replace.** Rostered = active QB/RB/WR/TE currently on an NFL
 * team (anyone who can score a non-passing TD). A player who has since dropped
 * off a roster keeps his entry with `active: false` and a null team, exactly as
 * refreshRoster treats him in the DB — so a lineup saved before a cutdown still
 * resolves, and the generated seed never flips a row back to pickable. Rewriting
 * the file from the dump alone would drop ~240 players every cutdown day.
 */
import { readFileSync, existsSync, writeFileSync, mkdirSync } from "fs";
import { fetchRoster } from "../lib/sleeper";

const PLAYERS_JSON = "public/players.json";
const SEED_SQL = "drizzle/seed-players.sql";

type PoolPlayer = {
  id: string;
  fullName: string;
  team: string | null;
  position: string;
  searchName: string;
  active: boolean;
};

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''");
}

function sqlText(value: string | null): string {
  return value === null ? "NULL" : `'${sqlEscape(value)}'`;
}

function readExistingPool(): PoolPlayer[] {
  if (!existsSync(PLAYERS_JSON)) return [];
  const raw: (Omit<PoolPlayer, "active"> & { active?: boolean })[] = JSON.parse(
    readFileSync(PLAYERS_JSON, "utf-8"),
  );
  // `active` postdates the first imports; anything written before it was, by
  // that import's own filter, rostered at the time.
  return raw.map((p) => ({ ...p, active: p.active ?? true }));
}

async function main() {
  const roster = await fetchRoster();
  const rosterIds = new Set(roster.map((p) => p.id));

  const pool = new Map<string, PoolPlayer>();
  for (const p of readExistingPool()) {
    // Not on a roster any more: keep the entry, drop it out of the pickable set.
    pool.set(p.id, rosterIds.has(p.id) ? p : { ...p, team: null, active: false });
  }
  for (const p of roster) {
    pool.set(p.id, {
      id: p.id,
      fullName: p.fullName,
      team: p.team,
      position: p.position,
      searchName: p.searchName,
      active: true,
    });
  }

  const merged = [...pool.values()].sort((a, b) => a.fullName.localeCompare(b.fullName));

  mkdirSync("public", { recursive: true });
  writeFileSync(PLAYERS_JSON, JSON.stringify(merged));

  mkdirSync("drizzle", { recursive: true });
  const values = merged
    .map(
      (p) =>
        `(${sqlText(p.id)}, ${sqlText(p.fullName)}, ${sqlText(p.team)}, ${sqlText(p.position)}, ${p.active}, ${sqlText(p.searchName)})`,
    )
    .join(",\n  ");

  // play_team is deliberately absent: it's the frozen 2025 label the 21
  // Generator reads and must survive every roster refresh (schema.ts).
  const sql = `-- Generated by scripts/import-players.ts — do not edit by hand.
INSERT INTO players (id, full_name, team, position, active, search_name)
VALUES
  ${values}
ON CONFLICT (id) DO UPDATE SET
  full_name = excluded.full_name,
  team = excluded.team,
  position = excluded.position,
  active = excluded.active,
  search_name = excluded.search_name;
`;
  writeFileSync(SEED_SQL, sql);

  const rostered = merged.filter((p) => p.active).length;
  console.log(
    `Wrote ${merged.length} players to ${PLAYERS_JSON} (${rostered} rostered, ${merged.length - rostered} retained but inactive)`,
  );
  console.log(`Wrote ${SEED_SQL} (run after migrations to populate the DB)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
